blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/incubus-network
    about: Join our Discord
  - name: ShapeShift Forum
    url: https://forum.incubus-network.com/
    about: Check out the forum
